apiVersion: v1
kind: ConfigMap
metadata:
  name: application-settings
data:
        MYSQL_ROOT_PASSWORD= {{ .Values.MYSQL_ROOT_PASSWORD }}
        MYSQL_ALLOW_EMPTY_PASSWORD= {{ .Values.MYSQL_ALLOW_EMPTY_PASSWORD }}
        MYSQL_USER= {{ .Values.MYSQL_USER }}
        MYSQL_PASSWORD= {{ .Values.MYSQL_PASSWORD }}
        MYSQL_DATABASE= {{ .Values.MYSQL_DATABASE }}

